// PRÉPA BREVET — Base de données des exercices
// 35 exercices

var data = [
  {
    id: "brevet-amerique-nord-2024-exo-01",
    fichier: "data/brevet-amerique-nord-2024-exo-01.html",
    titre: "affirmations — vrai ou faux justifié",
    source: "Brevet Amérique Nord 2024",
    annee: 2024,
    session: "Amérique Nord",
    notion: "Statistiques",
    notions: ["Statistiques", "Probabilités", "Géométrie"],
    points: 20
  },
  {
    id: "brevet-amerique-nord-2024-exo-02",
    fichier: "data/brevet-amerique-nord-2024-exo-02.html",
    titre: "programme de calcul",
    source: "Brevet Amérique Nord 2024",
    annee: 2024,
    session: "Amérique Nord",
    notion: "Algèbre et Fonctions",
    notions: ["Algèbre et Fonctions"],
    points: 20
  },
  {
    id: "brevet-amerique-nord-2024-exo-03",
    fichier: "data/brevet-amerique-nord-2024-exo-03.html",
    titre: "tarifs cinéma — fonctions & graphique",
    source: "Brevet Amérique Nord 2024",
    annee: 2024,
    session: "Amérique Nord",
    notion: "Fonctions et graphiques",
    notions: ["Fonctions et graphiques"],
    points: 20
  },
  {
    id: "brevet-amerique-nord-2024-exo-04",
    fichier: "data/brevet-amerique-nord-2024-exo-04.html",
    titre: "terrasse en béton — volume, périmètre & ratio",
    source: "Brevet Amérique Nord 2024",
    annee: 2024,
    session: "Amérique Nord",
    notion: "Volume",
    notions: ["Volume", "Périmètre", "Pythagore"],
    points: 20
  },
  {
    id: "brevet-amerique-nord-2024-exo-05",
    fichier: "data/brevet-amerique-nord-2024-exo-05.html",
    titre: "triangle équilatéral, thalès & scratch",
    source: "Brevet Amérique Nord 2024",
    annee: 2024,
    session: "Amérique Nord",
    notion: "Géométrie",
    notions: ["Géométrie", "Thalès", "Scratch"],
    points: 20
  },
  {
    id: "brevet-amerique-sud-2024-exo-01",
    fichier: "data/brevet-amerique-sud-2024-exo-01.html",
    titre: "QCM — 5 questions",
    source: "Brevet Amérique Sud 2024",
    annee: 2024,
    session: "Amérique Sud",
    notion: "Probabilités",
    notions: ["Probabilités", "Géométrie", "Thalès"],
    points: 20
  },
  {
    id: "brevet-amerique-sud-2024-exo-02",
    fichier: "data/brevet-amerique-sud-2024-exo-02.html",
    titre: "fonctions f et g — tableur & factorisation",
    source: "Brevet Amérique Sud 2024",
    annee: 2024,
    session: "Amérique Sud",
    notion: "Fonctions",
    notions: ["Fonctions", "Tableur", "Factorisation"],
    points: 20
  },
  {
    id: "brevet-amerique-sud-2024-exo-03",
    fichier: "data/brevet-amerique-sud-2024-exo-03.html",
    titre: "félins — probabilités, vitesse & géographie",
    source: "Brevet Amérique Sud 2024",
    annee: 2024,
    session: "Amérique Sud",
    notion: "Probabilités",
    notions: ["Probabilités", "Vitesse", "Pourcentages"],
    points: 20
  },
  {
    id: "brevet-amerique-sud-2024-exo-04",
    fichier: "data/brevet-amerique-sud-2024-exo-04.html",
    titre: "terrain en pente — pythagore, trigonométrie & volume",
    source: "Brevet Amérique Sud 2024",
    annee: 2024,
    session: "Amérique Sud",
    notion: "Pythagore",
    notions: ["Pythagore", "Trigonométrie", "Volume prisme"],
    points: 20
  },
  {
    id: "brevet-amerique-sud-2024-exo-05",
    fichier: "data/brevet-amerique-sud-2024-exo-05.html",
    titre: "bloc losange — scratch & figures géométriques",
    source: "Brevet Amérique Sud 2024",
    annee: 2024,
    session: "Amérique Sud",
    notion: "Scratch",
    notions: ["Scratch", "Géométrie", "Losange"],
    points: 20
  },
  {
    id: "brevet-asie-2024-exo-01",
    fichier: "data/brevet-asie-2024-exo-01.html",
    titre: "QCM — questionnaire à choix multiples",
    source: "Brevet Asie 2024",
    annee: 2024,
    session: "Asie",
    notion: "Arithmétique",
    notions: ["Arithmétique", "Géométrie", "Algèbre"],
    points: 20
  },
  {
    id: "brevet-asie-2024-exo-02",
    fichier: "data/brevet-asie-2024-exo-02.html",
    titre: "affirmations — vrai ou faux justifié",
    source: "Brevet Asie 2024",
    annee: 2024,
    session: "Asie",
    notion: "Géométrie",
    notions: ["Géométrie", "Probabilités"],
    points: 20
  },
  {
    id: "brevet-asie-2024-exo-03",
    fichier: "data/brevet-asie-2024-exo-03.html",
    titre: "pièce géométrique — arc, triangle, disque",
    source: "Brevet Asie 2024",
    annee: 2024,
    session: "Asie",
    notion: "Géométrie",
    notions: ["Géométrie", "Aires", "Trigonométrie"],
    points: 20
  },
  {
    id: "brevet-asie-2024-exo-04",
    fichier: "data/brevet-asie-2024-exo-04.html",
    titre: "terrasse en béton — volume, périmètre, peinture",
    source: "Brevet Asie 2024",
    annee: 2024,
    session: "Asie",
    notion: "Volume et Grandeurs",
    notions: ["Volume et Grandeurs", "Proportionnalité"],
    points: 20
  },
  {
    id: "brevet-asie-2024-exo-05",
    fichier: "data/brevet-asie-2024-exo-05.html",
    titre: "programme scratch — motif & figures",
    source: "Brevet Asie 2024",
    annee: 2024,
    session: "Asie",
    notion: "Scratch",
    notions: ["Scratch", "Géométrie", "Variables"],
    points: 20
  },
  {
    id: "brevet-centres-etrangers-2024-exo-01",
    fichier: "data/brevet-centres-etrangers-2024-exo-01.html",
    titre: "QCM — questionnaire à choix multiples",
    source: "Brevet Centres Étrangers 2024",
    annee: 2024,
    session: "Centres Étrangers",
    notion: "Puissances",
    notions: ["Puissances", "Vitesse", "Probabilités"],
    points: 20
  },
  {
    id: "brevet-centres-etrangers-2024-exo-02",
    fichier: "data/brevet-centres-etrangers-2024-exo-02.html",
    titre: "circuits d'entraînement",
    source: "Brevet Centres Étrangers 2024",
    annee: 2024,
    session: "Centres Étrangers",
    notion: "Arithmétique",
    notions: ["Arithmétique", "PGCD", "Multiples"],
    points: 20
  },
  {
    id: "brevet-centres-etrangers-2024-exo-03",
    fichier: "data/brevet-centres-etrangers-2024-exo-03.html",
    titre: "programme de calcul & fonction g",
    source: "Brevet Centres Étrangers 2024",
    annee: 2024,
    session: "Centres Étrangers",
    notion: "Algèbre et Fonctions",
    notions: ["Algèbre et Fonctions"],
    points: 20
  },
  {
    id: "brevet-centres-etrangers-2024-exo-04",
    fichier: "data/brevet-centres-etrangers-2024-exo-04.html",
    titre: "géométrie — triangle, angles, homothétie",
    source: "Brevet Centres Étrangers 2024",
    annee: 2024,
    session: "Centres Étrangers",
    notion: "Géométrie",
    notions: ["Géométrie", "Trigonométrie", "Homothétie"],
    points: 20
  },
  {
    id: "brevet-centres-etrangers-2024-exo-05",
    fichier: "data/brevet-centres-etrangers-2024-exo-05.html",
    titre: "chapeau de sorcier — cône & patron",
    source: "Brevet Centres Étrangers 2024",
    annee: 2024,
    session: "Centres Étrangers",
    notion: "Volume et Grandeurs",
    notions: ["Volume et Grandeurs", "Géométrie"],
    points: 20
  },
  {
    id: "brevet-metropole-septembre-2025-exo-01",
    fichier: "data/brevet-metropole-septembre-2025-exo-01.html",
    titre: "playlist d'Aurélie — dénombrement &amp; probabilités",
    source: "Brevet Métropole Septembre 2025",
    annee: 2025,
    session: "Métropole Septembre",
    notion: "Dénombrement",
    notions: ["Dénombrement", "Moyenne", "Probabilités"],
    points: 20
  },
  {
    id: "brevet-metropole-septembre-2025-exo-02",
    fichier: "data/brevet-metropole-septembre-2025-exo-02.html",
    titre: "QCM — 6 questions",
    source: "Brevet Métropole Septembre 2025",
    annee: 2025,
    session: "Métropole Septembre",
    notion: "Statistiques",
    notions: ["Statistiques", "Volume", "Notation scientifique"],
    points: 20
  },
  {
    id: "brevet-metropole-septembre-2025-exo-03",
    fichier: "data/brevet-metropole-septembre-2025-exo-03.html",
    titre: "triangles — Thalès &amp; trigonométrie",
    source: "Brevet Métropole Septembre 2025",
    annee: 2025,
    session: "Métropole Septembre",
    notion: "Thalès",
    notions: ["Thalès", "Pythagore", "Trigonométrie"],
    points: 20
  },
  {
    id: "brevet-metropole-septembre-2025-exo-04",
    fichier: "data/brevet-metropole-septembre-2025-exo-04.html",
    titre: "filtration de piscine — fonction affine",
    source: "Brevet Métropole Septembre 2025",
    annee: 2025,
    session: "Métropole Septembre",
    notion: "Fonction affine",
    notions: ["Fonction affine", "Graphique", "Équation"],
    points: 20
  },
  {
    id: "brevet-metropole-septembre-2025-exo-05",
    fichier: "data/brevet-metropole-septembre-2025-exo-05.html",
    titre: "table carrée — aires, transformation &amp; Scratch",
    source: "Brevet Métropole Septembre 2025",
    annee: 2025,
    session: "Métropole Septembre",
    notion: "Aire",
    notions: ["Aire", "Pourcentage", "Transformation"],
    points: 20
  },
  {
    id: "brevet-nouvelle-caledonie-2025-exo-01",
    fichier: "data/brevet-nouvelle-caledonie-2025-exo-01.html",
    titre: "5 questions — 3 réponses",
    source: "Brevet Nouvelle-Calédonie 2025",
    annee: 2025,
    session: "Nouvelle-Calédonie",
    notion: "Nombres premiers",
    notions: ["Nombres premiers", "Aire", "Fonctions"],
    points: 20
  },
  {
    id: "brevet-nouvelle-caledonie-2025-exo-02",
    fichier: "data/brevet-nouvelle-caledonie-2025-exo-02.html",
    titre: "trigonométrie &amp; vitesse",
    source: "Brevet Nouvelle-Calédonie 2025",
    annee: 2025,
    session: "Nouvelle-Calédonie",
    notion: "Trigonométrie",
    notions: ["Trigonométrie", "Pythagore", "Conversion"],
    points: 20
  },
  {
    id: "brevet-nouvelle-caledonie-2025-exo-03",
    fichier: "data/brevet-nouvelle-caledonie-2025-exo-03.html",
    titre: "fonctions affines &amp; équations",
    source: "Brevet Nouvelle-Calédonie 2025",
    annee: 2025,
    session: "Nouvelle-Calédonie",
    notion: "Calcul littéral",
    notions: ["Calcul littéral", "Fonctions", "Équation"],
    points: 20
  },
  {
    id: "brevet-nouvelle-caledonie-2025-exo-04",
    fichier: "data/brevet-nouvelle-caledonie-2025-exo-04.html",
    titre: "probabilités &amp; dénombrement",
    source: "Brevet Nouvelle-Calédonie 2025",
    annee: 2025,
    session: "Nouvelle-Calédonie",
    notion: "Probabilités",
    notions: ["Probabilités", "Issues", "Dénombrement"],
    points: 20
  },
  {
    id: "brevet-nouvelle-caledonie-2025-exo-05",
    fichier: "data/brevet-nouvelle-caledonie-2025-exo-05.html",
    titre: "thalès, aires &amp; triangles semblables",
    source: "Brevet Nouvelle-Calédonie 2025",
    annee: 2025,
    session: "Nouvelle-Calédonie",
    notion: "Thalès",
    notions: ["Thalès", "Angles", "Aires"],
    points: 20
  },
  {
    id: "brevet-polynesie-2025-exo-01",
    fichier: "data/brevet-polynesie-2025-exo-01.html",
    titre: "escalade — tableur &amp; statistiques",
    source: "Brevet Polynésie 2025",
    annee: 2025,
    session: "Polynésie",
    notion: "Tableur",
    notions: ["Tableur", "Statistiques", "Moyenne"],
    points: 20
  },
  {
    id: "brevet-polynesie-2025-exo-02",
    fichier: "data/brevet-polynesie-2025-exo-02.html",
    titre: "jardin botanique — géométrie &amp; trigonométrie",
    source: "Brevet Polynésie 2025",
    annee: 2025,
    session: "Polynésie",
    notion: "Pythagore",
    notions: ["Pythagore", "Thalès", "Trigonométrie"],
    points: 20
  },
  {
    id: "brevet-polynesie-2025-exo-03",
    fichier: "data/brevet-polynesie-2025-exo-03.html",
    titre: "QCM — 5 questions",
    source: "Brevet Polynésie 2025",
    annee: 2025,
    session: "Polynésie",
    notion: "Calcul",
    notions: ["Calcul", "Facteurs premiers", "Aire"],
    points: 20
  },
  {
    id: "brevet-polynesie-2025-exo-04",
    fichier: "data/brevet-polynesie-2025-exo-04.html",
    titre: "programme de calcul &amp; fonction affine",
    source: "Brevet Polynésie 2025",
    annee: 2025,
    session: "Polynésie",
    notion: "Calcul littéral",
    notions: ["Calcul littéral", "Fonctions", "Graphiques"],
    points: 20
  },
  {
    id: "brevet-polynesie-2025-exo-05",
    fichier: "data/brevet-polynesie-2025-exo-05.html",
    titre: "dé à 12 faces &amp; Scratch",
    source: "Brevet Polynésie 2025",
    annee: 2025,
    session: "Polynésie",
    notion: "Probabilités",
    notions: ["Probabilités", "Scratch", "Simulation"],
    points: 20
  }
];
